apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-harness-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-harness-react
  template:
    metadata:
      labels:
        app: sample-harness-react
    spec:
      containers:
      - name: sample-harness-react
        image: vivek756/react:latest