apiVersion: v1
kind: Service
metadata:
  name: sample-harness-react
spec:
  selector:
    app: sample-harness-react
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000